### PR TITLE
Replace Sami by Doctum

### PR DESCRIPTION
**Pull request by williamdes**
Hi ! :fr: 

I replaced Sami by [Doctum](https://github.com/code-lts/doctum#readme) the version I maintain 

Let me know what you think about my change

### CODE REVIEW

**Comment by williamdes** [comment]
cc @Vagnerlg

I replaced the logic by a Docker one because of the PHP version support complexity.
Should be alright now, Doctum is a fork of Sami btw

**Comment by williamdes** [comment]
cc @Vagnerlg

**Comment by vidalvasconcelos** [comment]
Thank you very much @williamdes  for your 
contribution and congratulations on your work at Doctum. 

There is currently a new version of Mongolid in progress, although its Pull Request does not offer any compatibility breaks, it is preferable to address them to this new version on `v3` branch.

**Comment by williamdes** [comment]
> Thank you very much @williamdes for your
> contribution and congratulations on your work at Doctum.
> 
> There is currently a new version of Mongolid in progress, although its Pull Request does not offer any compatibility breaks, it is preferable to address them to this new version on `v3` branch.

Hi @vidalvasconcelos !
Should I rebase on branch  v3 then ?

**Comment by vidalvasconcelos** [comment]
@williamdes I think the rebase will give you a lot of headaches, even the patch can be quite complex, as `v3` has big changes. Redoing your changes from the v3 branch might be a little simpler.

I'm really sorry about that. Let's make the contribution process clearer so that others aren't affected like you.

**Comment by williamdes** [comment]
> @williamdes I think the rebase will give you a lot of headaches, even the patch can be quite complex, as `v3` has big changes. Redoing your changes from the v3 branch might be a little simpler.
> 
> I'm really sorry about that. Let's make the contribution process clearer so that others don't get hurt like you.

No worries, I rebased it ;)
I have some good practice with git and QA branches, it was an easy fix: reset hard, cherry-pick commits from before

**Pull request merged**
